apiVersion: v1
kind: Service
metadata:
  name: scaling-service
spec:
  selector:
    app: scaling
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5001
    # targetPort: 5000
  # type: LoadBalancer
  type: NodePort


---
apiVersion: apps/v1
# apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: scaling
spec:
  selector:
    matchLabels:
      app: scaling
  replicas: 1
  template:
    metadata:
      labels:
        app: scaling
    spec:
      containers:
      - name: scaling
        image: scaling:v16.6
        # image: public.ecr.aws/m5r4d3y5/flink-jobs:q-table-jan21-v15
        imagePullPolicy: Never
        # imagePullPolicy: Always
        ports:
        # - containerPort: 5000
        - containerPort: 5001
