apiVersion: v1
kind: Service
metadata:
  name: scaling-service
spec:
  selector:
    app: scaling
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5001
  type: NodePort


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scaling
spec:
  selector:
    matchLabels:
      app: scaling
  replicas: 1
  template:
    metadata:
      labels:
        app: scaling
    spec:
      containers:
      - name: scaling
        image: public.ecr.aws/m5r4d3y5/flink-jobs:q-table-feb05-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
